# Generated by Django 4.2.6 on 2023-11-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='empresa',
            field=models.TextField(blank=True),
        ),
    ]
