# Generated by Django 4.2.6 on 2023-11-21 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_empresas_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuxListas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True)),
                ('fornecedor', models.CharField(blank=True, max_length=60, null=True)),
                ('qtde', models.IntegerField()),
                ('pedido', models.CharField(blank=True, max_length=10, null=True)),
                ('local', models.CharField(blank=True, max_length=60, null=True)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.listas')),
            ],
        ),
    ]
